services:
  postgres:
    image: postgres:13.5
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    networks:
      - valostrats
    volumes:
      - postgres:/var/lib/postgresql/data
    profiles:
      - 'db-standalone'
      - ''
  nestjs:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@postgres:5432/mydb
    ports:
      - '3100:3000'
    networks:
      - valostrats
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - 'backend'
      - ''

  nextjs:
    build: ./frontend
    ports:
      - '3003:3000'
    networks:
      - valostrats
    profiles:
      - 'frontend'
      - ''
networks:
  valostrats:
    driver: bridge
volumes:
  postgres: